name: ray_cluster
services:
  # MinIO object store service provides storage for checkpoints from Ray Train jobs
  minio:
    image: minio/minio
    container_name: minio
    restart: always
    expose:
      - "9000"
    ports:  
      - "9000:9000" 
      - "9001:9001"  
    environment:
      MINIO_ROOT_USER: "your-access-key"
      MINIO_ROOT_PASSWORD: "your-secret-key"
    healthcheck:
      test: timeout 5s bash -c ':> /dev/tcp/127.0.0.1/9000' || exit 1
      interval: 1s
      timeout: 10s
      retries: 5
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data 
  # When the minio service has started, launch a container with the minio client
  # and use it to create a bucket named ray
  minio-create-bucket:
    image: minio/mc
    depends_on:
      minio:
        condition: service_healthy
    entrypoint: >
      /bin/sh -c "
      mc alias set minio http://minio:9000 your-access-key your-secret-key &&
      if ! mc ls minio/ray; then
        mc mb minio/ray &&
        echo 'Bucket ray creatd'
      else
        echo 'Bucket ray already exists';
      fi"

  ray-head:
    image: rayproject/ray:2.42.1
    container_name: ray-head
    command: |
      /bin/sh -c "
      mkdir -p /tmp/ray && 
      chown -R root:root /tmp/ray &&
      ray metrics launch-prometheus &&
      ray start --head --port=6379 --dashboard-host=0.0.0.0 --block --metrics-export-port=8080"
    ports:
      - "6379:6379" 
      - "8265:8265" 
      - "8080:8080" 
      - "8090:8090" 
      - "9090:9090" 
    shm_size: '12g'
    volumes:
      - ray_tmp:/tmp/ray
    environment:
      - RAY_GRAFANA_HOST=http://grafana:3000
      - RAY_GRAFANA_IFRAME_HOST=http://${HOST_IP}:3000
      - RAY_PROMETHEUS_HOST=http://ray-head:9090
      - RAY_PROMETHEUS_NAME=Prometheus
      - AWS_ACCESS_KEY_ID=your-access-key     # for MinIO access
      - AWS_SECRET_ACCESS_KEY=your-secret-key
      - AWS_ENDPOINT_URL=http://minio:9000
    user: root

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    entrypoint: |
      /bin/sh -c "
      # Wait for config directory
      while [ ! -f /tmp/ray/session_latest/metrics/grafana/grafana.ini ]; do
        echo 'Waiting for Grafana config files...'
        sleep 2
      done
      
      # Start Grafana with copied config
      /run.sh --config /tmp/ray/session_latest/metrics/grafana/grafana.ini"
    ports:
      - "3000:3000"
    volumes:
      - grafana_storage:/var/lib/grafana
      - ray_tmp:/tmp/ray:ro
    environment:
      - GF_INSTALL_PLUGINS=grafana-piechart-panel
      - GF_PATHS_PROVISIONING=/tmp/ray/session_latest/metrics/grafana/provisioning
      - GF_SERVER_HTTP_ADDR=0.0.0.0
      - GF_DATABASE_TYPE=sqlite3
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_SECURITY_ALLOW_EMBEDDING=true
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_AUTH_PROXY_ENABLED=true
      - GF_AUTH_PROXY_AUTO_SIGN_UP=true
    depends_on:
      - ray-head

  ray-worker-1:
    image: rayproject/ray:2.42.1-gpu
    container_name: ray-worker-0
    command: ["ray", "start", "--address=ray-head:6379", "--num-cpus=32", "--num-gpus=1", "--block"]
    deploy:
      resources:
        reservations:
          devices:
            - driver: "nvidia"
              capabilities: ["gpu"]
              device_ids: ["0"]
    environment:
      - AWS_ACCESS_KEY_ID=your-access-key     # for MinIO access
      - AWS_SECRET_ACCESS_KEY=your-secret-key
      - AWS_ENDPOINT_URL=http://minio:9000
    shm_size: '12g'
    volumes:
      - food11:/mnt
    depends_on:
      - ray-head

  ray-worker-2:
    image: rayproject/ray:2.42.1-gpu
    container_name: ray-worker-1
    command: ["ray", "start", "--address=ray-head:6379", "--num-cpus=32", "--num-gpus=1", "--block"]
    deploy:
      resources:
        reservations:
          devices:
            - driver: "nvidia"
              capabilities: ["gpu"]
              device_ids: ["1"]
    environment:
      - AWS_ACCESS_KEY_ID=your-access-key     # for MinIO access
      - AWS_SECRET_ACCESS_KEY=your-secret-key
      - AWS_ENDPOINT_URL=http://minio:9000
    shm_size: '12g'
    volumes:
      - food11:/mnt
    depends_on:
      - ray-head

volumes:
  grafana_storage:
  ray_tmp:
  minio_data:
  food11:
    external: true  # Uses externally created volume