FROM quay.io/jupyter/pytorch-notebook:cuda12-latest

USER ${NB_UID}

# Install Lightning
RUN pip install --pre --no-cache-dir lightning && \
    fix-permissions "${CONDA_DIR}" && \
    fix-permissions "/home/${NB_USER}"

# Install MLFlow and pynvml library used by MLFlow for monitoring NVIDIA GPU
RUN pip install --pre --no-cache-dir pynvml && \
    pip install --pre --no-cache-dir mlflow && \
    fix-permissions "${CONDA_DIR}" && \
    fix-permissions "/home/${NB_USER}"