name: project37-etl

volumes:
  project37:

services:
  # To run it: docker compose -f docker-compose-etl.yaml run extract-data
  extract-data:
    container_name: etl_extract_data
    image: python:3.11
    user: root
    volumes:
      - project37:/data
    working_dir: /data
    command:
      - bash
      - -c
      - |
        set -e
        
        echo "Resetting dataset directory..."
        rm -rf /data/Project-37
        mkdir -p /data/Project-37
        cd /data/Project-37
        
        echo "Downloading MovieLens 1B tar..."
        curl -L https://files.grouplens.org/datasets/movielens/ml-20mx16x32.tar \
          -o ml-1b.tar
        
        echo "Extracting tar file..."
        tar -xf ml-1b.tar
        rm -f ml-1b.tar
        
        echo "Listing contents of /data after extract stage:"
        ls -l /data
