apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  namespace: project37-platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
        - name: prometheus
          image: prom/prometheus
          ports:
            - containerPort: 9090
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: project37-platform
spec:
  selector:
    app: prometheus
  ports:
    - port: 9090
      targetPort: 9090
  externalIPs:
    - {{ .Values.prometheus.externalIP }}
