version: "3.9"

services:
  jupyter:
    image: quay.io/jupyter/pytorch-notebook
    container_name: jupyter-data
    ports:
      - "8888:8888"
    shm_size: 8G
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - MOVIELENS_DATA_DIR=/mnt/data
    volumes:
      - ./serve-model-chi/workspace:/home/jovyan/work/

      - ~/data:/mnt/data:ro

    command: start-notebook.sh --NotebookApp.token=''
