apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: deploy-container-image
spec:
  entrypoint: deploy
  arguments:
    parameters:
    - name: environment
    - name: model-version

  templates:
  - name: deploy
    inputs:
      parameters:
      - name: environment
      - name: model-version
    container:
      image: argoproj/argocd:latest
      command: [sh, -c]
      args:
        - |
          echo "Deploying model {{inputs.parameters.model-version}} to {{inputs.parameters.environment}}..."
          tag="{{inputs.parameters.environment}}-1.1.{{inputs.parameters.model-version}}"
          app_name="project37-{{inputs.parameters.environment}}"

          argocd login argocd-server.argocd.svc.cluster.local \
            --username admin \
            --password "$ARGOCD_PASSWORD" \
            --insecure

          argocd app set "$app_name" --helm-set-string image.tag=$tag
          argocd app sync "$app_name"
      env:
        - name: ARGOCD_PASSWORD
          valueFrom:
            secretKeyRef:
              name: argocd-initial-admin-secret
              key: password
