
---
- name: Mount persistent volume and deploy MLflow platform with MinIO
  hosts: node1
  become: yes

  vars:
    # ── storage ────────────────────────────────────────────────────────────────
    minio_device: "/dev/vdb"
    root_mount_path: "/mnt/minio-data"          # one mount point
    minio_subdir: "{{ root_mount_path }}/minio"
    postgres_subdir: "{{ root_mount_path }}/postgres"

    # ── argocd / helm ─────────────────────────────────────────────────────────
    argocd_username: "admin"
    repo_path: "https://github.com/zuchuandatou/mlops-iac.git"
    app_name: "project37-platform"
    app_path: "k8s/platform"
    minio_access_key: "your-access-key"

  tasks:
    ###############################################################################
    # 1.  Format once (ext4) if the disk is blank
    ###############################################################################
    - name: Detect filesystem on {{ minio_device }}
      command: blkid -o value -s TYPE {{ minio_device }}
      register: fs_type
      failed_when: false
      changed_when: false

    - name: Format {{ minio_device }} as ext4 on first use
      filesystem:
        fstype: ext4
        dev: "{{ minio_device }}"
        force: yes
      when: fs_type.stdout == ""

    ###############################################################################
    # 2.  Mount the disk at a single root path  (/mnt/minio-data)
    ###############################################################################
    - name: Make root mount directory
      file:
        path: "{{ root_mount_path }}"
        state: directory
        mode: "0755"

    - name: Mount volume & ensure /etc/fstab
      mount:
        path: "{{ root_mount_path }}"
        src:  "{{ minio_device }}"
        fstype: ext4
        opts: defaults
        state: mounted        # → idempotent + fstab entry

    ###############################################################################
    # 3.  App‑specific sub‑directories
    ###############################################################################
    - name: Make MinIO data dir
      file:
        path: "{{ minio_subdir }}"
        state: directory
        mode: "0755"

    - name: Make Postgres data dir
      file:
        path: "{{ postgres_subdir }}"
        state: directory
        mode: "0700"
        owner: "999"          # postgres UID; adjust if different
        group: "999"

        
- name: Deploy MLflow platform via ArgoCD & Helm with MinIO secret handling
  hosts: node1
  become: yes
  vars:
    argocd_username: "admin"
    repo_path: "https://github.com/zuchuandatou/mlops-iac.git"
    target_rev: "zehao-li/cicd"
    app_name: "project37-platform"
    app_path: "k8s/platform"
    minio_access_key: "your-access-key"

  tasks:
    - name: Get ArgoCD admin password from Kubernetes secret
      command: >
        kubectl get secret -n argocd argocd-initial-admin-secret \
        -o jsonpath="{.data.password}"
      register: argocd_password_base64

    - name: Decode ArgoCD admin password
      shell: echo {{ argocd_password_base64.stdout }} | base64 --decode
      register: argocd_password

    - name: Log in to ArgoCD
      command: >
        argocd login localhost --username {{ argocd_username }} \
        --password "{{ argocd_password.stdout }}" --grpc-web --port-forward --port-forward-namespace=argocd
      register: login_result
      changed_when: false

    - name: Add repository to ArgoCD
      command: >
        argocd repo add {{ repo_path }} --port-forward --port-forward-namespace=argocd
      register: repo_result
      changed_when: "'Repository already exists' not in repo_result.stderr"

    - name: Detect external IP starting with 10.56
      set_fact:
        external_ip: "{{ ansible_all_ipv4_addresses | select('match', '^10\\.56\\..*') | list | first }}"

    - name: Ensure project37-platform namespace exists
      command: kubectl get namespace project37-platform
      register: ns_check
      failed_when: false
      changed_when: false

    - name: Create project37-platform namespace if missing
      when: ns_check.rc != 0
      command: kubectl create namespace project37-platform

    - name: Check if MinIO secret already exists
      command: kubectl get secret minio-credentials -n project37-platform
      register: minio_secret_check
      failed_when: false
      changed_when: false

    - name: Generate MinIO secret key
      when: minio_secret_check.rc != 0
      set_fact:
        minio_secret_key: "{{ lookup('password', '/dev/null length=20 chars=ascii_letters,digits') }}"

    - name: Create MinIO credentials secret
      when: minio_secret_check.rc != 0
      command: >
        kubectl create secret generic minio-credentials
        --namespace project37-platform
        --from-literal=accesskey={{ minio_access_key }}
        --from-literal=secretkey={{ minio_secret_key }}
      register: minio_secret_create

    - name: Get existing MinIO secret key if already exists
      when: minio_secret_check.rc == 0
      command: >
        kubectl get secret minio-credentials -n project37-platform -o jsonpath="{.data.secretkey}"
      register: existing_secret_b64

    - name: Decode existing MinIO secret key
      when: minio_secret_check.rc == 0
      set_fact:
        minio_secret_key: "{{ existing_secret_b64.stdout | b64decode }}"

    - name: Check if ArgoCD application exists
      command: >
        argocd app get {{ app_name }} --port-forward --port-forward-namespace=argocd
      register: app_check
      failed_when: false
      changed_when: false

    - name: Create ArgoCD Helm application if it does not exist
      when: app_check.rc != 0
      command: >
        argocd app create {{ app_name }} \
        --repo {{ repo_path }} \
        --path {{ app_path }} \
        --revision {{ target_rev }} \
        --dest-server https://kubernetes.default.svc \
        --dest-namespace "project37-platform" \
        --helm-set-string minio.externalIP={{ external_ip }} \
        --helm-set-string mlflow.externalIP={{ external_ip }} \
        --helm-set-string prometheus.externalIP={{ external_ip }} \
        --helm-set-string grafana.externalIP={{ external_ip }} \
        --port-forward --port-forward-namespace=argocd \
        --sync-policy automated --self-heal
      register: app_create

    - name: Update ArgoCD Helm application if it exists
      when: app_check.rc == 0
      command: >
        argocd app set {{ app_name }} \
        --revision {{ target_rev }} \
        --dest-namespace "project37-platform" \
        --helm-set-string minio.externalIP={{ external_ip }} \
        --helm-set-string mlflow.externalIP={{ external_ip }} \
        --helm-set-string prometheus.externalIP={{ external_ip }} \
        --helm-set-string grafana.externalIP={{ external_ip }} \
        --port-forward --port-forward-namespace=argocd
      register: app_update

    - name: Display MinIO credentials
      debug:
        msg: |
          MinIO Access Key: {{ minio_access_key }}
          MinIO Secret Key: {{ minio_secret_key }}
